#
# This file is maintained by salt!
#

server.host: "0.0.0.0"
server.port: 5601
#elasticsearch.url: "http://{{ pillar.elk.elasticsearch.host }}:{{ pillar.elk.elasticsearch.port }}"
elasticsearch.hosts: ["http://{{ pillar.elk.elasticsearch.host }}:{{ pillar.elk.elasticsearch.port }}"]
elasticsearch.ssl.verificationMode: none
elasticsearch.preserveHost: true
elasticsearch.requestTimeout: 300000
elasticsearch.shardTimeout: 0
kibana.index: ".kibana"
kibana.defaultAppId: "discover"
